# Generated by Django 3.2.7 on 2021-09-08 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('model', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2021)])),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
