# Generated by Django 3.2.7 on 2021-09-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
        ('cars', '0002_autoparkmodel_auto_park'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoParkModel',
            new_name='CarModel',
        ),
    ]
