# Generated by Django 3.2.7 on 2021-09-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pc',
            table='my_pc',
        ),
    ]
