# Generated by Django 3.2.7 on 2021-09-05 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('model', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(250), django.core.validators.MaxValueValidator(2000)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2021)])),
                ('number_of_passengers', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('max_range_of_flight', models.IntegerField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(50000)])),
            ],
            options={
                'db_table': 'airplanes',
            },
        ),
    ]
