# Generated by Django 3.2.7 on 2021-09-05 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanemodel',
            name='brand',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='airplanemodel',
            name='model',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
