# Generated by Django 3.2.7 on 2021-09-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoparkmodel',
            name='street',
        ),
    ]
