# Generated by Django 3.2.7 on 2021-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0002_remove_autoparkmodel_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparkmodel',
            name='street',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
